export const APP = {
    SET_USER_DATA: "SET_USER_DATA",
    SEARCH_USER: "SEARCH_USER",
    SET_USER: "SET_USER"
};

export const GET_USER = {
    GET_USER_PENDING: "GET_USER_PENDING",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_ERROR: "GET_USER_ERROR"
};
